language: bash
python:
  - "2.7"

services: docker

before_install:
  - docker pull manuelnvro/dockertraining:1.2

before_script:
- docker run -i -t -v $(pwd):/OpenIPSL manuelnvro/dockertraining:1.2 sh -c "python OpenIPSL/CI/modelCheck.py"
  
script:
  - docker run -i -t -v $(pwd):/OpenIPSL manuelnvro/dockertraining:1.2 sh -c "python OpenIPSL/CI/helloworld.py"
