language: bash
python:
  - "3.7"
git:
  depth: false

services: docker

before_script:
  - sudo docker pull manuelnvro/dockertraining:1.5
  - sudo docker run manuelnvro/dockertraining:1.5 sh -c "python3.7 modelCheck.py"


script:
- sudo docker run manuelnvro/dockertraining:1.5 sh -c "cd Fault; python3.7 FaultExcitersOpenModelica.py"
