language: bash
python:
  - "3.8"

services: docker

before_script:
  - sudo docker pull manuelnvro/dockertraining:1.5

script:
- sudo docker run --name citest -a stdout manuelnvro/dockertraining:1.5
- sudo docker logs -f citest

