language: bash
python:
  - "3.7"

services: docker

before_script:
  - sudo docker pull manuelnvro/dockertraining:1.5
  - sudo docker run manuelnvro/dockertraining:1.5 sh -c "cd Fault; python modelCheck.py"


script:
- sudo docker run --rm manuelnvro/dockertraining:1.4

