language: bash
python:
  - "3.5"

services: docker

before_install:
  - docker pull manuelnvro/dockertraining
  
script:
  - docker run -i -t -v $(pwd):/OpenIPSL manuelnvro/dockertraining:1.0 sh -c "python /CI/helloworld.py"
