language: bash
python:
  - "3.7"

services: docker

before_script:
  - sudo docker pull manuelnvro/dockertraining:1.6
  - sudo docker run manuelnvro/dockertraining:1.6 sh -c "python3.7 modelCheck.py"


script:
- sudo docker run manuelnvro/dockertraining:1.6 sh -c "python3.7 PythonRunAllOpenModelica.py"

