language: bash
python:
  - "3.7"

services: docker

before_script:
  - sudo docker pull manuelnvro/dockertraining:1.6
  - sudo docker run manuelnvro/dockertraining:1.6 sh -c "python3.7 modelCheck.py"


script:
#- sudo docker run manuelnvro/dockertraining:1.6 sh -c "cd Fault; python3.7 FaultRunAllOpenModelica.py"
- sudo docker run manuelnvro/dockertraining:1.6 sh -c "cd LoadVariation; python3.7 LoadVariationExcitersOpenModelica.py"
#- sudo docker run manuelnvro/dockertraining:1.6 sh -c "cd ReferenceStep; python3.7 ReferenceStepExcitersOpenModelica.py"

