language: bash
python:
  - "3.8"

services: docker

before_install:
  - sudo docker pull manuelnvro/dockertraining:1.5

before_script:
- docker run --name citest --rm manuelnvro/dockertraining:1.5

script:
- docker logs -f citest
