language: bash
python:
  - "3.8"

services: docker

before_script:
  - sudo docker build -t manuelnvro/dockertraining:1.5 .

script:
- docker run --name citest manuelnvro/dockertraining:1.5
- docker logs -f citest

