language: bash
python:
  - "3.8"

services: docker

before_install:
  - sudo docker pull manuelnvro/dockertraining:1.4

before_script:
- docker run -i -t -v $(pwd):/ manuelnvro/dockertraining:1.4 sh -c "python CI/helloworld.py"

  
script:
- docker run -i -t -v $(pwd):/ manuelnvro/dockertraining:1.4 sh -c "python CI/modelCheck.py"
