language: bash
python:
  - "3.8"

services: docker

before_install:
  - sudo docker build -t manuelnvro/dockertraining:1.4 .

before_script:
- docker run -i -t -v $(pwd):/OpenIPSL manuelnvro/dockertraining:1.2 sh -c "python /OpenIPSL/CI/syntaxCheck.py"

  
script:
- docker run -i -t -v $(pwd):/OpenIPSL manuelnvro/dockertraining:1.2 sh -c "python OpenIPSL/CI/helloworld.py"
