language: bash
python:
  - "2.7"

services: docker

before_install:
  - docker pull manuelnvro/dockertraining

script:
  - docker run -i -t -v $(pwd):/DockerTraining manuelnvro/dockertraining sh -c "python /DockerTraining/CI/DockerSample.py"
