language: bash
python:
  - "3.5"

services: docker

before_install:
  - docker pull manuelnvro/dockertraining:1.0

script:
  - docker run -ti -v $(pwd):/DockerTraining manuelnvro/dockertraining:1.0 bash 
