language: bash
python:
  - "3.7"

services: docker

before_script:
  - sudo docker pull manuelnvro/dockertraining:1.9
  #- sudo docker run manuelnvro/dockertraining:1.9 sh -c "python3.7 modelCheck.py"


script:
- sudo docker run manuelnvro/dockertraining:1.9 sh -c "python3.7 PythonRunAllOpenModelica.py"
#- sudo docker run manuelnvro/dockertraining:1.9 sh -c "cd LoadVariation; python3.7 LoadVariationRunAllOpenModelica.py"
#- sudo docker run manuelnvro/dockertraining:1.9 sh -c "cd ReferenceStep; python3.7 ReferenceStepExcitersOpenModelica.py"

