language: bash
python:
  - "3.8"

services: docker

before_script:
  - sudo docker pull manuelnvro/dockertraining:1.4
  - sudo docker run manuelnvro/dockertraining:1.4 sh -c "pwd ;ls; cd CI; ls; python modelCheck.py"


script:
- sudo docker run --rm manuelnvro/dockertraining:1.4

