language: bash
python:
  - "3.5"

services: docker

before_install:
  - docker pull manuelnvro/dockertraining:1.0
  
before_script:  
  - docker run -ti -v $(pwd):/DockerTraining manuelnvro/dockertraining:1.0 bash 
  
script:
  - docker run -i -t -v $(pwd):/OpenIPSL smartslab/openipsl sh -c "python /OpenIPSL/CI/syntaxCheck.py"
