language: bash
python:
  - "3.8"

services: docker

before_install:
  - sudo docker pull manuelnvro/dockertraining:1.5

before_script:
- docker run --name citest manuelnvro/dockertraining:1.5
- docker logs -f citest

