language: bash
python:
  - "3.5"

services: docker

before_install:
  - docker pull manuelnvro/dockertraining:1.1

before_script:
- docker run -i -t -v $(pwd):/OpenIPSL manuelnvro/dockertraining:1.1 sh -c "python /OpenIPSL/CI/syntaxcheck.py"
  
script:
  - docker run -i -t -v $(pwd):/OpenIPSL manuelnvro/dockertraining:1.1 sh -c "python /CI/helloworld.py"
